#development credentials
services:
 # signalflow-backend:
    #image: signalflow-backend
    #build:
    #  context: .
    #  dockerfile: Dockerfile
  postgres:
    image: postgres:16-alpine
    container_name: signalflow-postgres
    environment:
      POSTGRES_DB: signalflow
      POSTGRES_USER: signalflow
      POSTGRES_PASSWORD: signalflow123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U signalflow -d signalflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: signalflow-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@signalflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

